name: got-train-dt-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - scikit-learn
      - joblib
      - mltable
      - azureml-mlflow
      - mlflow<2.22
