channels:
- conda-forge
dependencies:
- python=3.10.19
- pip<=25.3
- pip:
  - mlflow==2.21.3
  - cloudpickle==2.2.1
  - numpy==2.2.6
  - pandas==2.3.3
  - pyarrow==19.0.1
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
